#cloud-config
output: {all: '| tee -a /var/log/cloud-init-output.log'}

groups:
  - ${docker_group}
  - ${oracle_group}

system_info:
  default_user:
    groups: [ ${docker_group} ]

users:
  - default
  - name: ${oracle_user}
    groups: [ ${oracle_group}, ${docker_group} ]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true
  - name: ${default_user}
    groups: [ ${oracle_group}, ${docker_group} ]

yum_repos:
  docker-ce-stable:
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    name: Docker CE Stable - $basearch
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: 0
    enabled: 1
#package_upgrade: true
#packages:
#  - git
#  - docker-ce
#  - docker-ce-cli
#  - containerd.io
runcmd:
  - yum install -y yum-utils
  - yum-config-manager --disable ol7_ksplice ol7_MySQL80*
  - yum-config-manager --enable ol7_developer ol7_developer_epel
  - yum clean all && yum update -y
  - yum install -y git docker-ce docker-ce-cli
  - groupmod -g ${oracle_gid} ${oracle_group}
  - usermod -u ${oracle_uid} ${oracle_user}
  - mkdir ${oradata_dir} && chown ${oracle_user}:${oracle_group} ${oradata_dir} && chmod g+w ${oradata_dir}
  - systemctl enable docker && systemctl start docker
  - runuser -l ${default_user} -c "git clone ${lab_repo_source} ~/${lab_repo_name} && chmod u+x ~/${lab_repo_name}/config/*sh"
  - runuser -l ${default_user} -c "~/${lab_repo_name}/config/setup_repo.sh"
  - runuser -l ${default_user} -c "~/${lab_repo_name}/config/setup_image.sh ${image_source} ${db_version} ${container_registry_pass} ${container_registry_user}"
  - runuser -l ${default_user} -c "docker images"
  - runuser -l ${default_user} -c "~/${lab_repo_name}/config/setup_container.sh ${run_container} ${db_version} ${container_name} ${docker_tns_port} ${oracle_sid} ${oracle_pdb} ${oradata_dir}"

final_message: "Installation complete at $UPTIME seconds"
